name: Premake on multiple platforms

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        Vendor\Binaries\Premake\Windows\premake5.exe --file=Test.lua vs2022
        msbuild /m /p:Configuration=${{matrix.build_type}} /p:Platform=x64 Eagle-Test.sln

    - name: Test
      working-directory: ${{env.GITHUB_WORKSPACE}}/Binaries/windows-x86_64/${{matrix.build_type}}/Test
      run: ./Test.exe
