name: Premake on multiple platforms

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build_windows:
    runs-on: windows-latest
    env:
      SOLUTION_FILE_PATH: .
      BUILD_CONFIGURATION: Release
    steps:
      - uses: actions/checkout@v4

      - name: Checkout FlightKit
        uses: actions/checkout@v4
        with:
          repository: github.com/kietran99/FlightKitCpp
          path: ../FlightKitCpp

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: |
          $ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
          $ToolkitPremakeDir = Join-Path $ScriptDir "..\..\FlightKitCpp\Premake" | Resolve-Path -ErrorAction Stop
          $GetPremakeScript = Join-Path $ToolkitPremakeDir "get_binaries.py"
          $PremakePath = & python $GetPremakeScript
          if (-not $PremakePath) {
              Write-Error "Failed to get Premake path from get_binaries.py"
              exit 1
          }
          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x64 ${{env.SOLUTION_FILE_PATH}}

      - name: Test
        working-directory: Binaries\windows-x86_64\${{env.BUILD_CONFIGURATION}}\Test
        run: .\Test.exe
